// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sptrs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/spacesprotocol/explorer-indexer/pkg/types"
)

const findLatestDelegationBySptr = `-- name: FindLatestDelegationBySptr :one
SELECT sptr_delegations.identifier, sptr_delegations.sptr, sptr_delegations.name, sptr_delegations.block_hash, sptr_delegations.txid, sptr_delegations.vout, sptr_delegations.revoked, sptr_delegations.revoked_block_hash, sptr_delegations.revoked_txid, sptr_delegations.revoked_vout
FROM sptr_delegations
JOIN blocks ON sptr_delegations.block_hash = blocks.hash
WHERE sptr_delegations.sptr = $1
  AND sptr_delegations.name = $2
  AND sptr_delegations.revoked = false
  AND blocks.orphan = false
ORDER BY blocks.height DESC, sptr_delegations.identifier DESC
LIMIT 1
`

type FindLatestDelegationBySptrParams struct {
	Sptr string
	Name string
}

func (q *Queries) FindLatestDelegationBySptr(ctx context.Context, arg FindLatestDelegationBySptrParams) (SptrDelegation, error) {
	row := q.db.QueryRow(ctx, findLatestDelegationBySptr, arg.Sptr, arg.Name)
	var i SptrDelegation
	err := row.Scan(
		&i.Identifier,
		&i.Sptr,
		&i.Name,
		&i.BlockHash,
		&i.Txid,
		&i.Vout,
		&i.Revoked,
		&i.RevokedBlockHash,
		&i.RevokedTxid,
		&i.RevokedVout,
	)
	return i, err
}

const findSpacePointerByOutpoint = `-- name: FindSpacePointerByOutpoint :one
SELECT space_pointers.identifier, space_pointers.block_hash, space_pointers.txid, space_pointers.vout, space_pointers.sptr, space_pointers.value, space_pointers.script_pubkey, space_pointers.data, space_pointers.spent_block_hash, space_pointers.spent_txid, space_pointers.spent_vin
FROM space_pointers
JOIN blocks ON space_pointers.block_hash = blocks.hash
WHERE space_pointers.txid = $1
  AND space_pointers.vout = $2
  AND blocks.orphan = false
`

type FindSpacePointerByOutpointParams struct {
	Txid types.Bytes
	Vout int32
}

func (q *Queries) FindSpacePointerByOutpoint(ctx context.Context, arg FindSpacePointerByOutpointParams) (SpacePointer, error) {
	row := q.db.QueryRow(ctx, findSpacePointerByOutpoint, arg.Txid, arg.Vout)
	var i SpacePointer
	err := row.Scan(
		&i.Identifier,
		&i.BlockHash,
		&i.Txid,
		&i.Vout,
		&i.Sptr,
		&i.Value,
		&i.ScriptPubkey,
		&i.Data,
		&i.SpentBlockHash,
		&i.SpentTxid,
		&i.SpentVin,
	)
	return i, err
}

const insertDelegation = `-- name: InsertDelegation :exec
INSERT INTO sptr_delegations (
    sptr,
    name,
    block_hash,
    txid,
    vout
)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDelegationParams struct {
	Sptr      string
	Name      string
	BlockHash types.Bytes
	Txid      types.Bytes
	Vout      int32
}

func (q *Queries) InsertDelegation(ctx context.Context, arg InsertDelegationParams) error {
	_, err := q.db.Exec(ctx, insertDelegation,
		arg.Sptr,
		arg.Name,
		arg.BlockHash,
		arg.Txid,
		arg.Vout,
	)
	return err
}

const insertSpacePointer = `-- name: InsertSpacePointer :exec
INSERT INTO space_pointers (
    block_hash,
    txid,
    vout,
    sptr,
    value,
    script_pubkey,
    data
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSpacePointerParams struct {
	BlockHash    types.Bytes
	Txid         types.Bytes
	Vout         int32
	Sptr         string
	Value        int64
	ScriptPubkey types.Bytes
	Data         *types.Bytes
}

func (q *Queries) InsertSpacePointer(ctx context.Context, arg InsertSpacePointerParams) error {
	_, err := q.db.Exec(ctx, insertSpacePointer,
		arg.BlockHash,
		arg.Txid,
		arg.Vout,
		arg.Sptr,
		arg.Value,
		arg.ScriptPubkey,
		arg.Data,
	)
	return err
}

const updateDelegationRevoked = `-- name: UpdateDelegationRevoked :exec
UPDATE sptr_delegations
SET revoked = true,
    revoked_block_hash = $1,
    revoked_txid = $2,
    revoked_vout = $3
WHERE block_hash = $4
  AND txid = $5
  AND vout = $6
`

type UpdateDelegationRevokedParams struct {
	RevokedBlockHash *types.Bytes
	RevokedTxid      *types.Bytes
	RevokedVout      pgtype.Int4
	BlockHash        types.Bytes
	Txid             types.Bytes
	Vout             int32
}

func (q *Queries) UpdateDelegationRevoked(ctx context.Context, arg UpdateDelegationRevokedParams) error {
	_, err := q.db.Exec(ctx, updateDelegationRevoked,
		arg.RevokedBlockHash,
		arg.RevokedTxid,
		arg.RevokedVout,
		arg.BlockHash,
		arg.Txid,
		arg.Vout,
	)
	return err
}

const updateSpacePointerSpender = `-- name: UpdateSpacePointerSpender :exec
UPDATE space_pointers
SET spent_block_hash = $1,
    spent_txid = $2,
    spent_vin = $3
WHERE block_hash = $4
  AND txid = $5
  AND vout = $6
`

type UpdateSpacePointerSpenderParams struct {
	SpentBlockHash *types.Bytes
	SpentTxid      *types.Bytes
	SpentVin       pgtype.Int4
	BlockHash      types.Bytes
	Txid           types.Bytes
	Vout           int32
}

func (q *Queries) UpdateSpacePointerSpender(ctx context.Context, arg UpdateSpacePointerSpenderParams) error {
	_, err := q.db.Exec(ctx, updateSpacePointerSpender,
		arg.SpentBlockHash,
		arg.SpentTxid,
		arg.SpentVin,
		arg.BlockHash,
		arg.Txid,
		arg.Vout,
	)
	return err
}
